package Pojos;
// Generated 10-dic-2018 12:05:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private String nhabitacion;
     private byte npersonas;
     private BigDecimal precio;
     private boolean ocupada;
     private Set reservas = new HashSet(0);
     private Set ocupacions = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(String nhabitacion, byte npersonas, BigDecimal precio, boolean ocupada) {
        this.nhabitacion = nhabitacion;
        this.npersonas = npersonas;
        this.precio = precio;
        this.ocupada = ocupada;
    }
    public Habitacion(String nhabitacion, byte npersonas, BigDecimal precio, boolean ocupada, Set reservas, Set ocupacions) {
       this.nhabitacion = nhabitacion;
       this.npersonas = npersonas;
       this.precio = precio;
       this.ocupada = ocupada;
       this.reservas = reservas;
       this.ocupacions = ocupacions;
    }
   
    public String getNhabitacion() {
        return this.nhabitacion;
    }
    
    public void setNhabitacion(String nhabitacion) {
        this.nhabitacion = nhabitacion;
    }
    public byte getNpersonas() {
        return this.npersonas;
    }
    
    public void setNpersonas(byte npersonas) {
        this.npersonas = npersonas;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public boolean isOcupada() {
        return this.ocupada;
    }
    
    public void setOcupada(boolean ocupada) {
        this.ocupada = ocupada;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


