package Pojos;
// Generated 10-dic-2018 12:05:14 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private OcupacionId id;
     private Habitacion habitacion;
     private String fechas;
     private String dni;

    public Ocupacion() {
    }

    public Ocupacion(OcupacionId id, Habitacion habitacion, String fechas, String dni) {
       this.id = id;
       this.habitacion = habitacion;
       this.fechas = fechas;
       this.dni = dni;
    }
   
    public OcupacionId getId() {
        return this.id;
    }
    
    public void setId(OcupacionId id) {
        this.id = id;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public String getFechas() {
        return this.fechas;
    }
    
    public void setFechas(String fechas) {
        this.fechas = fechas;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }




}


