package Pojos;
// Generated 10-dic-2018 12:05:14 by Hibernate Tools 4.3.1



/**
 * OcupacionId generated by hbm2java
 */
public class OcupacionId  implements java.io.Serializable {


     private String nhabitacion;
     private String fechae;

    public OcupacionId() {
    }

    public OcupacionId(String nhabitacion, String fechae) {
       this.nhabitacion = nhabitacion;
       this.fechae = fechae;
    }
   
    public String getNhabitacion() {
        return this.nhabitacion;
    }
    
    public void setNhabitacion(String nhabitacion) {
        this.nhabitacion = nhabitacion;
    }
    public String getFechae() {
        return this.fechae;
    }
    
    public void setFechae(String fechae) {
        this.fechae = fechae;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcupacionId) ) return false;
		 OcupacionId castOther = ( OcupacionId ) other; 
         
		 return ( (this.getNhabitacion()==castOther.getNhabitacion()) || ( this.getNhabitacion()!=null && castOther.getNhabitacion()!=null && this.getNhabitacion().equals(castOther.getNhabitacion()) ) )
 && ( (this.getFechae()==castOther.getFechae()) || ( this.getFechae()!=null && castOther.getFechae()!=null && this.getFechae().equals(castOther.getFechae()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNhabitacion() == null ? 0 : this.getNhabitacion().hashCode() );
         result = 37 * result + ( getFechae() == null ? 0 : this.getFechae().hashCode() );
         return result;
   }   


}


